from pydantic import BaseModel, Field
from typing import Annotated
import operator


class Question(BaseModel):
    """
    Data structure to store the list of questions that needs to be answered by the focus group personas.
    """
    id: str
    question: str


class AgentInput(BaseModel):
    """
    Input structure the agent takes from the end-user. The user writes single prompt and that gets transformed
    into this data structure.
    """
    focus_group_description: str
    persona_count: int
    questions: list[Question]
    review_guidance: str


class Persona(BaseModel):
    """
    Focus group personas synthesized to review the video content. This data structure stores relevant information
    about the persona itself.
    """
    id: str
    name: str
    bio: str
    demographics: str


class PersonasList(BaseModel):
    personas: list[Persona]


class Annotation(BaseModel):
    """
    Data structure to store the annotations generated by the focus group personas. These are annotations of the
    content video with the persona commenting on specific timestamps.
    """
    timestamp_sec: int
    comment: str
    score: int # 1-10


class QuestionResponse(BaseModel):
    """
    Data structure to store the persona's response to individual questions.
    """
    question_id: str
    answer: str
    score: int # 1-10


class ContentReview(BaseModel):
    """
    A collective data structure to store all the reviews by every focus group persona on the content video.
    """
    persona_id: str
    answers: list[QuestionResponse]
    annotations: list[Annotation]


class ContentReviewOptMixin(BaseModel):
    reviews: Annotated[list[ContentReview], operator.add] = Field(default_factory=list)


class AgentState(ContentReviewOptMixin):
    """
    Data structure to store the LangGraph agent state. This will be persisted in a database.
    """
    run_id: str
    user_prompt: str
    content_cache_key: str
    agent_input: AgentInput | None = None
    personas: list[Persona] = Field(default_factory=list)


class PersonaAgentState(AgentState):
    persona_id: str
